set (omni_root "$ENV{OMNI_ROOT}")
set (omni_dllver "414")
set (omnithread_dllver "34")
set (rtm_root "$ENV{RTM_ROOT}")
set (rtm_dllver "100")
set (rtm_version "1.0.0")
set (coil_dllver "")
set (omni_includes "\"${omni_root}\\include\"")
set (omni_libdir "\"${omni_root}\\lib\\x86_win32\"")
set (omni_bin "\"${omni_root}\\bin\\x86_win32\"")
set (omni_lib "omniORB${omni_dllver}_rt.lib omniDynamic${omni_dllver}_rt.lib omnithread${omnithread_dllver}_rt.lib")
set (omni_libd "omniORB${omni_dllver}_rtd.lib omniDynamic${omni_dllver}_rtd.lib omnithread${omnithread_dllver}_rtd.lib")
set (rtm_includes "\"${rtm_root}\";\"${rtm_root}\\rtm\\idl\"")
set (rtm_libdir "\"${rtm_root}\\bin\"")
set (rtm_bin "\"${rtm_root}\\bin\";\"${rtm_root}\\build\"")
set (rtm_path "${rtm_bin};${omni_bin}")
set (rtm_libd "RTC${rtm_dllver}d.lib ${coil_libd} ${omni_libd} advapi32.lib ws2_32.lib mswsock.lib ${user_libd}")
set (rtm_lib "RTC${rtm_dllver}.lib ${coil_lib} ${omni_lib} advapi32.lib ws2_32.lib mswsock.lib ${user_lib}")
set (rtm_idlc "omniidl")
set (rtm_idlflags "-bcxx -Wba -nf")
set (coil_lib "coil${coil_dllver}.lib")
set (coil_libd "coil${coil_dllver}d.lib")
